services:
  sku-analytics-monitor:
    build:
      context: ./server1
      dockerfile: Dockerfile # Verifique se o nome é exatamente este
    ports:
      - "8501:8501"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./server1:/app
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - sku-network

  # neo4j:
  #   image: neo4j:5.15.0-community
  #   container_name: neo4j-sku-analytics
  #   ports:
  #     - "7474:7474" # Interface HTTP (Navegador)
  #     - "7687:7687" # Protocolo Bolt (Para conectar o Python)
  #   volumes:
  #     - ./neo4j/data:/data
  #     - ./neo4j/logs:/logs
  #     - ./neo4j/conf:/conf
  #   environment:
  #     # Defina uma senha forte!
  #     - NEO4J_AUTH=neo4j/sua_senha_segura
  #   restart: always

  logistica-sku-analytics:
    container_name: logistica-sku-analytics
    build:
      context: ./server2
      dockerfile: Dockerfile # Verifique se este arquivo está DENTRO da pasta server2
    ports:
      - "8502:8501"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./server2:/app
    environment:
      - PYTHONUNBUFFERED=1
    # networks:
    #   - sku-network

  monitor-sentinel:
    build:
      context: ./server1
    container_name: monitor-sentinel
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./server1:/app
    command: ["python", "alert_worker.py"]
    restart: always
  

  ollama:
    image: ollama/ollama
    container_name: ollama-brain
    network_mode: host
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    # networks:
    #   - sku-network


networks:
  sku-network:
    driver: bridge

volumes:
  ollama_data: