apiVersion: apps/v1
kind: Deployment
metadata:
  name: azdevops-agent
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azdevops-agent
  template:
    metadata:
      labels:
        app: azdevops-agent
    spec:
      containers:
      - name: agent
        image: "mcr.microsoft.com/azure-pipelines/vsts-agent:latest"
        securityContext:
          privileged: true
        env:
          - name: VSTS_URL
            value: "https://dev.azure.com/faluz"
          - name: VSTS_ACCOUNT
            value: "faluz" #
          - name: VSTS_TOKEN
            value: "BpZj0jEuB0QR92LtrEcCcAD0iGd8N12vui5qySEzXRoqspDkwdjMJQQJ99CCACAAAAAAAAAAAAASAZDO1i9F"
          - name: AZP_POOL
            value: "Agente-PoC-Fabio" # Nome que você definiu no Terraform
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: docker-socket
      volumes:
      - name: docker-socket
        hostPath:
          path: /var/run/docker.sock