bundle:
  name: app

targets:
  dev:
    mode: development
    default: true
    workspace:
      host: https://adb-7405613152344883.3.azuredatabricks.net/

resources:
  jobs:
    sample_job:
      name: "[${bundle.target}] sample_job"
      tasks:
        - task_key: python_task
          new_cluster:
            # Trocamos para a versão ML nativa (sem Docker)
            spark_version: "13.3.x-cpu-ml-scala2.12"
            node_type_id: "Standard_DS3_v2"
            num_workers: 0
            
            # Configurações obrigatórias para Single Node
            spark_conf:
              spark.databricks.cluster.profile: "singleNode"
              spark.master: "local[*]"
            
            custom_tags:
              ResourceClass: "SingleNode"
              
            data_security_mode: "SINGLE_USER"

          # Instalamos o CatBoost e TensorFlow via PyPI, já que tiramos o Docker
          libraries:
            - pypi:
                package: catboost
            - pypi:
                package: tensorflow

          notebook_task:
            # Caminho relativo ao notebook (removi a barra inicial '/')
            notebook_path: ./notebook.ipynb